//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public System.Guid ConId { get; set; }
        public Nullable<System.Guid> ConversationIdUser1 { get; set; }
        public Nullable<System.Guid> ConversationIdUser2 { get; set; }
        public string UserGroup { get; set; }
        public string Msg { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public string MsgDuration { get; set; }
        public Nullable<System.Guid> User1Id { get; set; }
        public Nullable<System.Guid> User2Id { get; set; }
    }
}
